version: "3.8"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alex
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"

  python-app:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo

